[theme]

# Primary accent for interactive elements
primaryColor = '#1C3879'

# Background color for the main content area
backgroundColor = '#F1F1F1'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#D6E6FE'

# Color used for almost all text
textColor = '#000000'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
